"""Generate the scoped token CSS that web/theme_preview.html needs.

    python web/build_theme_preview.py

WHY THIS EXISTS. The preview sheet shows both candidate palettes at once. Both
candidate files declare their tokens on ``:root``, so importing both makes the
one that loads last win for the entire document and the two blocks render
identically. The fix is to re-scope each file's declarations to its own
selector -- and to GENERATE that, never retype it, because a hand-copied
palette in a preview is a second source of truth that drifts from the one the
site ships. Step 5 of phase (e) fixed exactly that class of bug in the
limitations lists; repeating it here for colour would be worse, since a
preview's whole job is to be what you are choosing between.

It rewrites only the selector. Every value, comment and ordering is carried
across byte for byte.
"""

from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
CSS = HERE / "assets/css"

VARIANTS = [
    ("tokens-a-light.css", ".variant--a", "A -- light"),
    # Variant B is the APPLIED theme, so the preview reads tokens.css itself
    # rather than a copy. The sheet can then never show a variant B that
    # differs from the one the site ships.
    ("tokens.css", ".variant--b", "B -- dark ember, APPLIED"),
]

OUT = CSS / "theme-preview-vars.css"

ROOT_BLOCK = re.compile(r":root\s*\{(.*?)\n\}", re.S)


def main() -> int:
    parts = [
        "/* GENERATED by web/build_theme_preview.py -- do not edit.\n"
        " *\n"
        " * Each candidate token file declares on :root. Importing two of them\n"
        " * would make the later one win for the whole document, so each block's\n"
        " * declarations are re-scoped to the variant that shows it. Only the\n"
        " * selector changes; every value is carried across unedited.\n"
        " *\n"
        " * Regenerate after editing either candidate file.\n"
        " */\n"
    ]

    for filename, selector, label in VARIANTS:
        src = CSS / filename
        if not src.exists():
            print("missing: %s" % src)
            return 1
        text = src.read_text(encoding="utf-8")
        blocks = ROOT_BLOCK.findall(text)
        if not blocks:
            print("no :root block in %s" % filename)
            return 1
        body = "\n".join(blocks)
        decls = re.findall(r"(--[a-z0-9-]+)\s*:\s*([^;]+);", body)
        parts.append("\n/* ---- variant %s, from %s ---- */\n%s {\n%s\n}\n"
                     % (label, filename, selector,
                        "\n".join("  %s: %s;" % (k, v.strip()) for k, v in decls)))
        print("%-22s -> %-12s  %d tokens" % (filename, selector, len(decls)))

    OUT.write_text("".join(parts), encoding="utf-8")
    print("wrote %s (%d bytes)" % (OUT.relative_to(HERE.parent).as_posix(),
                                   OUT.stat().st_size))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
